spring:
  springfox:
    documentation:
      auto-startup: false
  mvc:
    pathmatch:
      matching-strategy: ANT_PATH_MATCHER
  thymeleaf:
    cache: false
    check-template-location: true
  servlet:
    multipart:
      enabled: true
      max-file-size: 200MB
      max-request-size: 215MB
  datasource:
    url: jdbc:mysql://localhost:3306/mini-project-java?useUnicode=yes&characterEncoding=UTF-8&allowPublicKeyRetrieval=true&useSSL=false
    username: root
    password: 123456aA
  jpa:
    properties:
      hibernate:
        show_sql: true
        format_sql: true
        hbm2ddl:
          auto: update
  server:
    servlet:
      context-path: /
  logging:
    level:
      root: info
      file:
        name: log/dev.log